# Generated by Django 5.2.5 on 2025-08-12 17:33

import django.db.models.deletion
import stream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(default=stream.models.generate_uuid, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding', models.JSONField(null=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='stream.person')),
            ],
            options={
                'unique_together': {('person', 'expression')},
            },
        ),
    ]
