# Generated by Django 5.2.5 on 2025-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
